FROM python:3.9


WORKDIR /app

# Install OS dependencies
RUN apt-get update && apt-get install -qq -y \
    git gcc build-essential libpq-dev --fix-missing --no-install-recommends \ 
    && apt-get clean

# Make sure we are using latest pip
RUN pip install --upgrade pip



# Copy requirements.txt
COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY ./py_script/ /app/


ENV PYTHONPATH "${PYTHONPATH}:/app/"

EXPOSE 8000

CMD ["uvicorn","api:app","--host","0.0.0.0"]
